-- The purpose of this specific filter is to modify the HTML output generated by Pandoc by adding the target="_blank" 
-- attribute to all HTTP links (http or https). This attribute, when applied to an HTML anchor (<a>) element, 
-- instructs the browser to open the link in a new tab or window, rather than navigating away from the current page.

-- By adding this attribute to HTTP links, the filter ensures that when users click on such links in the converted 
-- HTML document, the linked content will open in a new tab, which can be a desirable user experience, especially 
-- when navigating away from the original document temporarily.

-- Add target="_blank" attributes to all http links in a Pandoc document
-- @param link (table) The link element to be processed
-- @return (table) The modified link element with target="_blank" attribute added if it's an http link

local function add_target_blank (link)
    -- Check if the link's target (href attribute) starts with 'http'
    if string.match(link.target, '^http') then  
        -- If the condition is met, set the target attribute to '_blank'
        link.attributes.target = '_blank'
    end
    -- Return the modified link element
    return link
end

return {
    { Link = add_target_blank }
}
