# Simple workflow for building the resume in different formats and deploying them to GitHub Pages
name: Build and deploy the resume to GitHub Pages
on:
  # Runs on pushes targeting resume.md on the default branch
  push:
    branches:
      - main
    paths:
      - 'resume.md'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install pandoc and context
      run: |
        sudo apt update
        sudo apt install -y pandoc context
        sudo luarocks install luasocket

    - name: Build resume
      run: make all

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
