name: Build and Deploy Resume

on:
  push:
    branches:
      - main
    paths:
      - 'resume.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install pandoc and context
      run: |
        sudo apt update
        sudo apt install -y pandoc context

    - name: Build resume
      run: |
        make all
        rm ./output/*.log
        rm ./output/*.tex
        rm ./output/*.tuc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
